export const SOCIAL_TYPE = {
    NEW_FOLLOWER: 'NEW_FOLLOWER',
    NEW_FOLLOWERS: 'NEW_FOLLOWERS',
    NEW_REFFERAL: 'NEW_REFFERAL',
    NEW_REFFERALS: 'NEW_REFFERALS',
    FUTURES_CALLING: 'FUTURES_CALLING',
    FUTURES_ADD_VOL: 'FUTURES_ADD_VOL',
    FUTURES_EDIT_TP_SL: 'FUTURES_EDIT_TP_SL',
    FUTURE_OPENED_SEND_TO_COPIER: 'FUTURE_OPENED_SEND_TO_COPIER',
    FUTURE_LIQUIDATE_SEND_TO_COPIER: 'FUTURE_LIQUIDATE_SEND_TO_COPIER',
    FUTURE_HIT_SL_SEND_TO_COPIER: 'FUTURE_HIT_SL_SEND_TO_COPIER',
    FUTURE_HIT_TP_SEND_TO_COPIER: 'FUTURE_HIT_TP_SEND_TO_COPIER',
    FUTURE_CLOSE_SEND_TO_COPIER: 'FUTURE_CLOSE_SEND_TO_COPIER',
    NEW_COPIER: 'NEW_COPIER',
    FOLLOWING_TP: 'FOLLOWING_TP',
    FOLLOWING_PROFIT: 'FOLLOWING_PROFIT',
    FUTURE_CANCEL_SEND_TO_COPIER: 'FUTURE_CANCEL_SEND_TO_COPIER'
};
